### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by macdhollister** [adambennett/StS-DuelistMod#10] opened 2020-01-13 05:07 UTC
Mod isn't working for me, it crashes on startup.
Debug steps taken:
Ran game with required dependencies only WITHOUT duelist activated (i.e. `BaseMod v. 5.15.1`, `GifTheSpireLib v. 1.0.5`, and `StSLib v. 1.17.1`). This launched the game with no issues. Activating Duelist Mod (v. 2.878.0 -- btw that's a ton of minor version bumps haha) made it crash on launch with the following log.

--------------------------------------------------------------------------------------------

```
Running with debug mode turned ON...

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (07-17-2019)
 - ModTheSpire (3.14.1)
Mod list:
 - basemod (5.15.1)
 - stslib (1.17.1)
 - GifTheSpireLib (1.0.5)
 - duelistmod (2.878.0)

Begin patching...
Patching enums...
java.lang.RuntimeException: failed to browse jar
	at org.scannotation.archiveiterator.JarIterator.setNext(JarIterator.java:52)
	at org.scannotation.archiveiterator.JarIterator.next(JarIterator.java:59)
	at org.scannotation.AnnotationDB.scanArchives(AnnotationDB.java:326)
	at com.evacipated.cardcrawl.modthespire.Patcher.patchEnums(Patcher.java:107)
	at com.evacipated.cardcrawl.modthespire.Patcher.patchEnums(Patcher.java:98)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:351)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:269)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: invalid distance code
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at java.util.jar.JarInputStream.read(JarInputStream.java:207)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
	at java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142)
	at java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179)
	at org.scannotation.archiveiterator.JarIterator.setNext(JarIterator.java:43)
	... 7 more
```

**Comment by adambennett** [comment] 2020-01-14 02:50
I'm closing this because I can't reproduce it on my end, even on the main branch. If this issue persists after tomorrow's Watcher update, feel free to reopen it.

**Closed by adambennett** 2020-01-14 02:50 UTC
